[Interface]
PrivateKey = ${REVERSE_PROXY_PRIVATE_KEY}
Address = 10.0.0.0/24
ListenPort = 40917

[Peer]
PublicKey = ${ORACLE_1_PUBLIC_KEY}
AllowedIPs = 10.0.0.1/32
Endpoint = vpn.durundur.online:40917
PersistentKeepalive = 25

[Peer]
PublicKey = ${ORACLE_2_PUBLIC_KEY}
AllowedIPs = 10.0.0.2/32
Endpoint = vpn.durundur.online:40917
PersistentKeepalive = 25

[Peer]
PublicKey = ${VPN_PUBLIC_KEY}
AllowedIPs = 10.0.0.254/32
Endpoint = vpn.durundur.online:40917
PersistentKeepalive = 25