[Interface]
PrivateKey = ${REVERSE_PROXY_PRIVATE_KEY}
Address = 10.0.0.1/24
ListenPort = 40917
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = ${ORACLE_1_PUBLIC_KEY}
AllowedIPs = 10.0.0.11/32
PersistentKeepalive = 25

[Peer]
PublicKey = ${ORACLE_2_PUBLIC_KEY}
AllowedIPs = 10.0.0.22/32
PersistentKeepalive = 25

[Peer]
PublicKey = ${VPN_PUBLIC_KEY}
AllowedIPs = 10.0.0.254/32
PersistentKeepalive = 25