[Interface]
PrivateKey = ${ORACLE_1_PRIVATE_KEY}
Address = 10.77.0.11/32

[Peer]
PublicKey = ${REVERSE_PROXY_PUBLIC_KEY}
AllowedIPs = 10.77.0.1/24
Endpoint = vpn.durundur.online:40917
PersistentKeepalive = 25
