[Interface]
PrivateKey = ${ORACLE_1_PRIVATE_KEY}
Address = 10.0.0.1/32

[Peer]
PublicKey = ${REVERSE_PROXY_PUBLIC_KEY}
AllowedIPs = 10.0.0.0/24
Endpoint = vpn.durundur.online:40917
PersistentKeepalive = 25
