[Interface]
PrivateKey = ${VPN_PRIVATE_KEY}
Address = 10.0.0.254/32

[Peer]
PublicKey = ${REVERSE_PROXY_PUBLIC_KEY}
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = vpn.durundur.online:40917
PersistentKeepalive = 25
